# Generated by Django 5.1.5 on 2025-01-31 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
    ]
