# Generated by Django 3.1.1 on 2020-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20200919_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrlaggregatedblockdata',
            name='block_timestamp_seconds_max',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrlaggregatedblockdata',
            name='block_timestamp_seconds_mean',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrlaggregatedblockdata',
            name='block_timestamp_seconds_min',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
