# Generated by Django 5.1.5 on 2025-01-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20250131_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrlblockchaintransactions',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrlblockchaintransactions',
            name='transaction_hash',
            field=models.CharField(max_length=128),
        ),
    ]
