# Generated by Django 5.1.5 on 2025-01-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_qrlblockchaintransactions_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrlblockchaintransactions',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qrlblockchaintransactions',
            name='token_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qrlblockchaintransactions',
            name='transaction_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='qrlblockchaintransactions',
            name='transaction_receiving_wallet_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='qrlblockchaintransactions',
            name='transaction_sending_wallet_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='qrlwalletaddress',
            name='wallet_address',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
