# Generated by Django 5.1.5 on 2025-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_qrlaggregatedtransactiondata_total_amount_transfered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrlblockchainmisseditems',
            name='failed_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
