# Generated by Django 5.1.5 on 2025-03-19 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_emissiondata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmissionData',
            new_name='QrlBlockchainEmission',
        ),
    ]
