# Generated by Django 3.1.1 on 2020-10-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20201021_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrlblockchaintransactions',
            old_name='block_timestamp_seconds',
            new_name='block_found_datetime',
        ),
    ]
