# Generated by Django 5.1.5 on 2025-03-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_rename_emissiondata_qrlblockchainemission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrlblockchainemission',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='qrlblockchainemission',
            table='qrl_blockchain_emission',
        ),
    ]
