# Generated by Django 3.1.1 on 2020-10-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20201021_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrlblockchainblocks',
            name='block_updated_timestamp',
        ),
        migrations.RemoveField(
            model_name='qrlblockchaintransactions',
            name='transaction_updated_timestamp',
        ),
        migrations.RemoveField(
            model_name='qrlwalletaddress',
            name='address_updated_date',
        ),
    ]
