# Generated by Django 3.1.1 on 2020-10-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_auto_20201021_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrlblockchaintransactions',
            old_name='transaction_added_timestamp',
            new_name='transaction_added_datetime',
        ),
        migrations.RenameField(
            model_name='qrlwalletaddress',
            old_name='address_added_date',
            new_name='address_added_datetime',
        ),
    ]
