# Generated by Django 3.1.1 on 2020-10-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_auto_20201021_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrlblockchaintransactions',
            name='transaction_slave_pk',
        ),
    ]
