# Generated by Django 3.1.1 on 2020-11-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_auto_20201129_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrlwalletaddress',
            name='wallet_type',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
